In [1]:
# UFC PREDICTION MODEL

In [53]:
from bs4 import BeautifulSoup as bs 
import requests as req

In [54]:
# UFC URL

url = 'http://www.ufcstats.com/statistics/fighters'
req.get(url)

In [55]:
html = req.get(url).text
sopa = bs(html, 'html.parser')

In [57]:
cabeceras = sopa.find('table').find('tr')  
filas = sopa.find('table').find_all('tr')[2:]

In [58]:
cabeceras = [e.text.strip() for e in cabeceras.find_all('th')]

In [59]:
[e.text.strip() for e in filas[1].find_all('td')]

['Danny',
 'Abbadi',
 'The Assassin',
 '5\' 11"',
 '155 lbs.',
 '--',
 'Orthodox',
 '4',
 '6',
 '0',
 '']

In [60]:
tabla = [[e.text.strip() for e in f.find_all('td')] for f in filas]

In [61]:
import pandas as pd

In [62]:
mcgregor = pd.DataFrame(tabla, columns=cabeceras)
mcgregor

,First,Last,Nickname,Ht.,Wt.,Reach,Stance,W,L,D,Belt
0,Tom,Aaron,,--,155 lbs.,--,,5,3,0,
1,Danny,Abbadi,The Assassin,"5' 11""",155 lbs.,--,Orthodox,4,6,0,
2,Nariman,Abbasov,Bayraktar,"5' 8""",155 lbs.,"66.0""",Orthodox,28,4,0,
3,David,Abbott,Tank,"6' 0""",265 lbs.,--,Switch,10,15,0,
4,Hamdy,Abdelwahab,The Hammer,"6' 2""",264 lbs.,"72.0""",Southpaw,5,0,0,
5,Shamil,Abdurakhimov,Abrek,"6' 3""",235 lbs.,"76.0""",Orthodox,20,8,0,
6,Hiroyuki,Abe,Abe Ani,"5' 6""",145 lbs.,--,Orthodox,8,15,3,
7,Daichi,Abe,,"5' 11""",170 lbs.,"71.0""",Orthodox,6,2,0,
8,Papy,Abedi,Makambo,"5' 11""",185 lbs.,--,Southpaw,10,4,0,
9,Ricardo,Abreu,Demente,"5' 11""",185 lbs.,--,Orthodox,5,1,0,
10,Klidson,Abreu,White Bear,"6' 0""",205 lbs.,"74.0""",Orthodox,15,4,0,
11,Cyborg,Abreu,,--,--,--,,0,0,0,
12,Daniel,Acacio,,"5' 8""",180 lbs.,--,Orthodox,30,18,0,
13,John,Adajar,The Outlaw,"5' 9""",170 lbs.,"75.0""",Orthodox,6,2,0,
14,Scott,Adams,,"6' 0""",225 lbs.,--,Southpaw,8,1,0,
15,Juan,Adams,The Kraken,"6' 5""",265 lbs.,"80.0""",Orthodox,5,3,0,
16,Anthony,Adams,Sugafoot,"6' 1""",185 lbs.,"76.0""",Orthodox,8,2,0,
17,Zarrukh,Adashev,The Lion,"5' 5""",125 lbs.,"65.0""",Southpaw,4,4,0,
18,Israel,Adesanya,The Last Stylebender,"6' 4""",185 lbs.,"80.0""",Switch,24,3,0,
19,Sam,Adkins,The Experience,"6' 3""",225 lbs.,--,Orthodox,7,20,2,
20,Nick,Agallar,,"5' 8""",155 lbs.,--,Orthodox,24,6,0,
21,Mariya,Agapova,Demonslayer,"5' 6""",125 lbs.,"68.0""",Southpaw,10,4,0,
22,Marcelo,Aguiar,,"5' 10""",170 lbs.,--,Orthodox,2,3,1,
23,Fabio,Aguiar,,"6' 0""",185 lbs.,--,,17,1,0,
24,Edwin,Aguilar,Tigre,"5' 10""",185 lbs.,--,,26,19,0,

In [63]:
pd.read_html('http://www.ufcstats.com/statistics/fighters?char=a&page=1')[0]

,First,Last,Nickname,Ht.,Wt.,Reach,Stance,W,L,D,Belt
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tom,Aaron,NaN,--,155 lbs.,--,NaN,5.0,3.0,0.0,NaN
2,Danny,Abbadi,The Assassin,"5' 11""",155 lbs.,--,Orthodox,4.0,6.0,0.0,NaN
3,Nariman,Abbasov,Bayraktar,"5' 8""",155 lbs.,"66.0""",Orthodox,28.0,4.0,0.0,NaN
4,David,Abbott,Tank,"6' 0""",265 lbs.,--,Switch,10.0,15.0,0.0,NaN
5,Hamdy,Abdelwahab,The Hammer,"6' 2""",264 lbs.,"72.0""",Southpaw,5.0,0.0,0.0,NaN
6,Shamil,Abdurakhimov,Abrek,"6' 3""",235 lbs.,"76.0""",Orthodox,20.0,8.0,0.0,NaN
7,Hiroyuki,Abe,Abe Ani,"5' 6""",145 lbs.,--,Orthodox,8.0,15.0,3.0,NaN
8,Daichi,Abe,NaN,"5' 11""",170 lbs.,"71.0""",Orthodox,6.0,2.0,0.0,NaN
9,Papy,Abedi,Makambo,"5' 11""",185 lbs.,--,Southpaw,10.0,4.0,0.0,NaN
10,Ricardo,Abreu,Demente,"5' 11""",185 lbs.,--,Orthodox,5.0,1.0,0.0,NaN
11,Klidson,Abreu,White Bear,"6' 0""",205 lbs.,"74.0""",Orthodox,15.0,4.0,0.0,NaN
12,Cyborg,Abreu,NaN,--,--,--,NaN,0.0,0.0,0.0,NaN
13,Daniel,Acacio,NaN,"5' 8""",180 lbs.,--,Orthodox,30.0,18.0,0.0,NaN
14,John,Adajar,The Outlaw,"5' 9""",170 lbs.,"75.0""",Orthodox,6.0,2.0,0.0,NaN
15,Scott,Adams,NaN,"6' 0""",225 lbs.,--,Southpaw,8.0,1.0,0.0,NaN
16,Juan,Adams,The Kraken,"6' 5""",265 lbs.,"80.0""",Orthodox,5.0,3.0,0.0,NaN
17,Anthony,Adams,Sugafoot,"6' 1""",185 lbs.,"76.0""",Orthodox,8.0,2.0,0.0,NaN
18,Zarrukh,Adashev,The Lion,"5' 5""",125 lbs.,"65.0""",Southpaw,4.0,4.0,0.0,NaN
19,Israel,Adesanya,The Last Stylebender,"6' 4""",185 lbs.,"80.0""",Switch,24.0,3.0,0.0,NaN
20,Sam,Adkins,The Experience,"6' 3""",225 lbs.,--,Orthodox,7.0,20.0,2.0,NaN
21,Nick,Agallar,NaN,"5' 8""",155 lbs.,--,Orthodox,24.0,6.0,0.0,NaN
22,Mariya,Agapova,Demonslayer,"5' 6""",125 lbs.,"68.0""",Southpaw,10.0,4.0,0.0,NaN
23,Marcelo,Aguiar,NaN,"5' 10""",170 lbs.,--,Orthodox,2.0,3.0,1.0,NaN
24,Fabio,Aguiar,NaN,"6' 0""",185 lbs.,--,NaN,17.0,1.0,0.0,NaN
25,Edwin,Aguilar,Tigre,"5' 10""",185 lbs.,--,NaN,26.0,19.0,0.0,NaN

In [64]:
url = 'http://www.ufcstats.com/statistics/fighters?char=a&page=2'

In [85]:
lst_df = []

for i in range(1, 9):
    print(i)
    url = f'http://www.ufcstats.com/statistics/fighters?char=a&page={i}'
    mcgregor = pd.read_html(url)[0]
    lst_df.append(df)

1
2
3
4
5
6
7
8

In [86]:
mcgregor = pd.concat(lst_df)
mcgregor.reset_index(drop = True, inplace = True)
mcgregor

,First,Last,Nickname,Ht.,Wt.,Reach,Stance,W,L,D,Belt
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Antonio,Arroyo,NaN,"6' 3""",185 lbs.,"73.0""",Orthodox,9.0,5.0,0.0,NaN
2,Gilles,Arsene,NaN,"5' 9""",190 lbs.,--,Southpaw,1.0,1.0,0.0,NaN
3,Veta,Arteaga,NaN,"5' 7""",125 lbs.,--,NaN,3.0,1.0,0.0,NaN
4,Cesar,Arzamendia,Goku,"5' 11""",155 lbs.,--,Orthodox,8.0,3.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
195,Bazigit,Atajev,Volk,"6' 1""",230 lbs.,--,Orthodox,17.0,1.0,0.0,NaN
196,Rich,Attonito,The Raging Bull,"5' 10""",170 lbs.,"72.0""",Orthodox,10.0,5.0,0.0,NaN
197,Olivier,Aubin-Mercier,The Canadian Gangster,"5' 9""",155 lbs.,"70.0""",Southpaw,11.0,5.0,0.0,NaN
198,Pat,Audinwood,Awesomely Awesome,"6' 0""",155 lbs.,--,Orthodox,11.0,2.0,1.0,NaN
199,Jose,Augusto,Gugu,"6' 3""",251 lbs.,--,NaN,6.0,2.0,0.0,NaN

In [87]:
mcgregor.dropna(how='all', inplace= True)
mcgregor.reset_index(drop = True, inplace = True)
mcgregor

,First,Last,Nickname,Ht.,Wt.,Reach,Stance,W,L,D,Belt
0,Antonio,Arroyo,NaN,"6' 3""",185 lbs.,"73.0""",Orthodox,9.0,5.0,0.0,NaN
1,Gilles,Arsene,NaN,"5' 9""",190 lbs.,--,Southpaw,1.0,1.0,0.0,NaN
2,Veta,Arteaga,NaN,"5' 7""",125 lbs.,--,NaN,3.0,1.0,0.0,NaN
3,Cesar,Arzamendia,Goku,"5' 11""",155 lbs.,--,Orthodox,8.0,3.0,0.0,NaN
4,Teddy,Ash,Bear,"6' 1""",185 lbs.,"73.0""",Switch,14.0,5.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
187,Bazigit,Atajev,Volk,"6' 1""",230 lbs.,--,Orthodox,17.0,1.0,0.0,NaN
188,Rich,Attonito,The Raging Bull,"5' 10""",170 lbs.,"72.0""",Orthodox,10.0,5.0,0.0,NaN
189,Olivier,Aubin-Mercier,The Canadian Gangster,"5' 9""",155 lbs.,"70.0""",Southpaw,11.0,5.0,0.0,NaN
190,Pat,Audinwood,Awesomely Awesome,"6' 0""",155 lbs.,--,Orthodox,11.0,2.0,1.0,NaN
191,Jose,Augusto,Gugu,"6' 3""",251 lbs.,--,NaN,6.0,2.0,0.0,NaN

In [91]:
pd.read_html('http://www.ufcstats.com/statistics/fighters?char=a&page=all')[0].dropna(how='all')

,First,Last,Nickname,Ht.,Wt.,Reach,Stance,W,L,D,Belt
1,Tom,Aaron,NaN,--,155 lbs.,--,NaN,5.0,3.0,0.0,NaN
2,Danny,Abbadi,The Assassin,"5' 11""",155 lbs.,--,Orthodox,4.0,6.0,0.0,NaN
3,Nariman,Abbasov,Bayraktar,"5' 8""",155 lbs.,"66.0""",Orthodox,28.0,4.0,0.0,NaN
4,David,Abbott,Tank,"6' 0""",265 lbs.,--,Switch,10.0,15.0,0.0,NaN
5,Hamdy,Abdelwahab,The Hammer,"6' 2""",264 lbs.,"72.0""",Southpaw,5.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
210,Abu,Azaitar,Captain Morocco,"5' 9""",185 lbs.,"76.0""",Orthodox,14.0,4.0,1.0,NaN
211,Ottman,Azaitar,Bulldozer,"5' 8""",155 lbs.,"71.0""",Switch,13.0,2.0,0.0,NaN
212,Luiz,Azeredo,NaN,"5' 9""",154 lbs.,--,Orthodox,15.0,10.0,0.0,NaN
213,Luciano,Azevedo,NaN,"6' 3""",161 lbs.,--,Orthodox,17.0,9.0,1.0,NaN
214,Hunter,Azure,NaN,"5' 8""",145 lbs.,"69.0""",Orthodox,9.0,2.0,0.0,NaN

In [89]:
# proyecto estructura

# 1. data extraction (scrapping, apis, o database)
# 2. data cleaning, data performing, maquillaje con el objetivo de operar con los datos y encaminarte hacia las conclusiones
# 3. hallazgos y presentación
# 4. Proximos pasos, hacia donde va el proyecto

In [92]:
mcgregor.head()

,First,Last,Nickname,Ht.,Wt.,Reach,Stance,W,L,D,Belt
0,Antonio,Arroyo,NaN,"6' 3""",185 lbs.,"73.0""",Orthodox,9.0,5.0,0.0,NaN
1,Gilles,Arsene,NaN,"5' 9""",190 lbs.,--,Southpaw,1.0,1.0,0.0,NaN
2,Veta,Arteaga,NaN,"5' 7""",125 lbs.,--,NaN,3.0,1.0,0.0,NaN
3,Cesar,Arzamendia,Goku,"5' 11""",155 lbs.,--,Orthodox,8.0,3.0,0.0,NaN
4,Teddy,Ash,Bear,"6' 1""",185 lbs.,"73.0""",Switch,14.0,5.0,0.0,NaN

In [94]:
mcgregor['win_ratio'] = mcgregor.W / (mcgregor.W + mcgregor.L + mcgregor.D)

In [95]:
mcgregor.head()

,First,Last,Nickname,Ht.,Wt.,Reach,Stance,W,L,D,Belt,win_ratio
0,Antonio,Arroyo,NaN,"6' 3""",185 lbs.,"73.0""",Orthodox,9.0,5.0,0.0,NaN,0.642857
1,Gilles,Arsene,NaN,"5' 9""",190 lbs.,--,Southpaw,1.0,1.0,0.0,NaN,0.500000
2,Veta,Arteaga,NaN,"5' 7""",125 lbs.,--,NaN,3.0,1.0,0.0,NaN,0.750000
3,Cesar,Arzamendia,Goku,"5' 11""",155 lbs.,--,Orthodox,8.0,3.0,0.0,NaN,0.727273
4,Teddy,Ash,Bear,"6' 1""",185 lbs.,"73.0""",Switch,14.0,5.0,0.0,NaN,0.736842

In [96]:
mcgregor.shape

(192, 12)

In [98]:
mcgregor['loss_ratio'] = mcgregor.L / (mcgregor.W + mcgregor.L + mcgregor.D)

In [99]:
mcgregor.head()

,First,Last,Nickname,Ht.,Wt.,Reach,Stance,W,L,D,Belt,win_ratio,loss_ratio
0,Antonio,Arroyo,NaN,"6' 3""",185 lbs.,"73.0""",Orthodox,9.0,5.0,0.0,NaN,0.642857,0.357143
1,Gilles,Arsene,NaN,"5' 9""",190 lbs.,--,Southpaw,1.0,1.0,0.0,NaN,0.500000,0.500000
2,Veta,Arteaga,NaN,"5' 7""",125 lbs.,--,NaN,3.0,1.0,0.0,NaN,0.750000,0.250000
3,Cesar,Arzamendia,Goku,"5' 11""",155 lbs.,--,Orthodox,8.0,3.0,0.0,NaN,0.727273,0.272727
4,Teddy,Ash,Bear,"6' 1""",185 lbs.,"73.0""",Switch,14.0,5.0,0.0,NaN,0.736842,0.263158

In [100]:
mcgregor['decision_ratio'] = mcgregor.D / (mcgregor.W + mcgregor.L + mcgregor.D)

In [103]:
mcgregor.head()

,First,Last,Nickname,Ht.,Wt.,Reach,Stance,W,L,D,Belt,win_ratio,loss_ratio,decision_ratio
0,Antonio,Arroyo,NaN,"6' 3""",185 lbs.,"73.0""",Orthodox,9.0,5.0,0.0,NaN,0.642857,0.357143,0.0
1,Gilles,Arsene,NaN,"5' 9""",190 lbs.,--,Southpaw,1.0,1.0,0.0,NaN,0.500000,0.500000,0.0
2,Veta,Arteaga,NaN,"5' 7""",125 lbs.,--,NaN,3.0,1.0,0.0,NaN,0.750000,0.250000,0.0
3,Cesar,Arzamendia,Goku,"5' 11""",155 lbs.,--,Orthodox,8.0,3.0,0.0,NaN,0.727273,0.272727,0.0
4,Teddy,Ash,Bear,"6' 1""",185 lbs.,"73.0""",Switch,14.0,5.0,0.0,NaN,0.736842,0.263158,0.0

In [105]:
mcgregor['Win-Loss Difference'] = df['W'] - df['L']

In [106]:
mcgregor.head()

,First,Last,Nickname,Ht.,Wt.,Reach,Stance,W,L,D,Belt,win_ratio,loss_ratio,decision_ratio,Win-Loss Difference
0,Antonio,Arroyo,NaN,"6' 3""",185 lbs.,"73.0""",Orthodox,9.0,5.0,0.0,NaN,0.642857,0.357143,0.0,NaN
1,Gilles,Arsene,NaN,"5' 9""",190 lbs.,--,Southpaw,1.0,1.0,0.0,NaN,0.500000,0.500000,0.0,4.0
2,Veta,Arteaga,NaN,"5' 7""",125 lbs.,--,NaN,3.0,1.0,0.0,NaN,0.750000,0.250000,0.0,0.0
3,Cesar,Arzamendia,Goku,"5' 11""",155 lbs.,--,Orthodox,8.0,3.0,0.0,NaN,0.727273,0.272727,0.0,2.0
4,Teddy,Ash,Bear,"6' 1""",185 lbs.,"73.0""",Switch,14.0,5.0,0.0,NaN,0.736842,0.263158,0.0,5.0

In [107]:
import pandas as pd
mcgregor = mcgregor.drop('decision_ratio', axis=1)

In [108]:
mcgregor.head()

,First,Last,Nickname,Ht.,Wt.,Reach,Stance,W,L,D,Belt,win_ratio,loss_ratio,Win-Loss Difference
0,Antonio,Arroyo,NaN,"6' 3""",185 lbs.,"73.0""",Orthodox,9.0,5.0,0.0,NaN,0.642857,0.357143,NaN
1,Gilles,Arsene,NaN,"5' 9""",190 lbs.,--,Southpaw,1.0,1.0,0.0,NaN,0.500000,0.500000,4.0
2,Veta,Arteaga,NaN,"5' 7""",125 lbs.,--,NaN,3.0,1.0,0.0,NaN,0.750000,0.250000,0.0
3,Cesar,Arzamendia,Goku,"5' 11""",155 lbs.,--,Orthodox,8.0,3.0,0.0,NaN,0.727273,0.272727,2.0
4,Teddy,Ash,Bear,"6' 1""",185 lbs.,"73.0""",Switch,14.0,5.0,0.0,NaN,0.736842,0.263158,5.0

In [109]:
mcgregor = mcgregor.drop('D', axis=1)

In [110]:
mcgregor.head()

,First,Last,Nickname,Ht.,Wt.,Reach,Stance,W,L,Belt,win_ratio,loss_ratio,Win-Loss Difference
0,Antonio,Arroyo,NaN,"6' 3""",185 lbs.,"73.0""",Orthodox,9.0,5.0,NaN,0.642857,0.357143,NaN
1,Gilles,Arsene,NaN,"5' 9""",190 lbs.,--,Southpaw,1.0,1.0,NaN,0.500000,0.500000,4.0
2,Veta,Arteaga,NaN,"5' 7""",125 lbs.,--,NaN,3.0,1.0,NaN,0.750000,0.250000,0.0
3,Cesar,Arzamendia,Goku,"5' 11""",155 lbs.,--,Orthodox,8.0,3.0,NaN,0.727273,0.272727,2.0
4,Teddy,Ash,Bear,"6' 1""",185 lbs.,"73.0""",Switch,14.0,5.0,NaN,0.736842,0.263158,5.0

In [111]:
mcgregor = mcgregor.drop('Belt', axis=1)

In [112]:
mcgregor.head()

,First,Last,Nickname,Ht.,Wt.,Reach,Stance,W,L,win_ratio,loss_ratio,Win-Loss Difference
0,Antonio,Arroyo,NaN,"6' 3""",185 lbs.,"73.0""",Orthodox,9.0,5.0,0.642857,0.357143,NaN
1,Gilles,Arsene,NaN,"5' 9""",190 lbs.,--,Southpaw,1.0,1.0,0.500000,0.500000,4.0
2,Veta,Arteaga,NaN,"5' 7""",125 lbs.,--,NaN,3.0,1.0,0.750000,0.250000,0.0
3,Cesar,Arzamendia,Goku,"5' 11""",155 lbs.,--,Orthodox,8.0,3.0,0.727273,0.272727,2.0
4,Teddy,Ash,Bear,"6' 1""",185 lbs.,"73.0""",Switch,14.0,5.0,0.736842,0.263158,5.0

In [113]:
mcgregor = mcgregor.drop('Nickname', axis=1)

In [115]:
mcgregor

,First,Last,Ht.,Wt.,Reach,Stance,W,L,win_ratio,loss_ratio,Win-Loss Difference
0,Antonio,Arroyo,"6' 3""",185 lbs.,"73.0""",Orthodox,9.0,5.0,0.642857,0.357143,NaN
1,Gilles,Arsene,"5' 9""",190 lbs.,--,Southpaw,1.0,1.0,0.500000,0.500000,4.0
2,Veta,Arteaga,"5' 7""",125 lbs.,--,NaN,3.0,1.0,0.750000,0.250000,0.0
3,Cesar,Arzamendia,"5' 11""",155 lbs.,--,Orthodox,8.0,3.0,0.727273,0.272727,2.0
4,Teddy,Ash,"6' 1""",185 lbs.,"73.0""",Switch,14.0,5.0,0.736842,0.263158,5.0
...,...,...,...,...,...,...,...,...,...,...,...
187,Bazigit,Atajev,"6' 1""",230 lbs.,--,Orthodox,17.0,1.0,0.944444,0.055556,NaN
188,Rich,Attonito,"5' 10""",170 lbs.,"72.0""",Orthodox,10.0,5.0,0.666667,0.333333,NaN
189,Olivier,Aubin-Mercier,"5' 9""",155 lbs.,"70.0""",Southpaw,11.0,5.0,0.687500,0.312500,NaN
190,Pat,Audinwood,"6' 0""",155 lbs.,--,Orthodox,11.0,2.0,0.785714,0.142857,NaN
191,Jose,Augusto,"6' 3""",251 lbs.,--,NaN,6.0,2.0,0.750000,0.250000,NaN

In [116]:
mcgregor.head()

,First,Last,Ht.,Wt.,Reach,Stance,W,L,win_ratio,loss_ratio,Win-Loss Difference
0,Antonio,Arroyo,"6' 3""",185 lbs.,"73.0""",Orthodox,9.0,5.0,0.642857,0.357143,NaN
1,Gilles,Arsene,"5' 9""",190 lbs.,--,Southpaw,1.0,1.0,0.500000,0.500000,4.0
2,Veta,Arteaga,"5' 7""",125 lbs.,--,NaN,3.0,1.0,0.750000,0.250000,0.0
3,Cesar,Arzamendia,"5' 11""",155 lbs.,--,Orthodox,8.0,3.0,0.727273,0.272727,2.0
4,Teddy,Ash,"6' 1""",185 lbs.,"73.0""",Switch,14.0,5.0,0.736842,0.263158,5.0